### PR TITLE
Started working on autoupdater

### PR DESCRIPTION
**Pull request by TheButlah**
Code WIP and not ready for review

### CODE REVIEW

**Comment by Eirenliel** [comment]
Why? We discussed it previously, server should update everything.

**Comment by TheButlah** [comment]
> Why? We discussed it previously, server should update everything.

This is not the firmware updater, it's the updater for the GUI server overlay, feeder, and driver

@loucass003 thought it should be a separate app, and I figured that was simple. If you have it in the server executable itself, doesn't that mean that you can't overwrite the executable? Hence it needs to be a separate file?

**Comment by Eirenliel** [comment]
Doesn't matter which file it needs be, but SlimeVR is installed as a whole package, so everything should be updated from one single place! Do not make people update different apps! This should be handled by one thing, either by the server, or by separate update that updates everything.

**Comment by TheButlah** [comment]
> This should be handled by one thing, either by the server, or by separate update that updates everything

This is the latter? I'm confused 

Unless you mean "everything including firmware"? You can't update firmware at the same time, that would mean the server GUI etc only ever updates when all trackers are available

**Comment by Eirenliel** [comment]
> > This should be handled by one thing, either by the server, or by separate update that updates everything
> 
> This is the latter? I'm confused

It was I who was confused, because the repo was "SlimeVR-Overlay" and there was no reason why it would be overlay's job to autoupdate SlimeVR.

**Pull request merged**
