### PR TITLE
Fix ESP32 not compilling

### LINKED ISSUE #162: [Firmware] ESP32 can't compile because of atomics
It seems [radium is trying to use atomics](https://github.com/SlimeVR/SlimeVR-Rust/actions/runs/4009664483/jobs/6906602412) in ESP32 and its failing to build

### PR DESCRIPTION
**Pull request by ImUrX**
Fixes #162

### CODE REVIEW

**Comment by ImUrX** [comment]
Couldn't ``cargo update`` because ``riscv-rt 0.10`` got yanked. Had to update ESP deps :/

**Review by TheButlah — DISMISSED** [review]

**Comment by TheButlah** [comment]
Looks like 32c3 fails

**Comment by TheButlah** [comment]
> Couldn't `cargo update` because `riscv-rt 0.10` got yanked. Had to update ESP deps :/

~~You generally don't need to `cargo update` when you add a new dependency. Cargo update updates *all* deps but editing the toml file will update only the deps necessary to get the version you want.~~

Looks like for patches specifically, I was wrong. You do still have to run cargo update for those.

**Comment by ImUrX** [comment]
esp-rs/esp-hal#367, seems we got problems in ``hal``

**Comment by TheButlah** [comment]
I wonder if this is fixed now

**Comment by ImUrX** [comment]
Yeah but no release from the esp-rs team yet

**Comment by TheButlah** [comment]
I don't mind patching to git commits, is that viable?

**Comment by TheButlah** [comment]
Superseded by #193

**Pull request closed without merging**
