### PR TITLE
Revert "Preliminary zero-IQ port of VQF to Rust "

### PR DESCRIPTION
**Pull request by TheButlah**
Reverts SlimeVR/SlimeVR-Rust#149

Reverting because I never got approval from @Noxime for this:

Screenshot 2023-01-27 at 12 35 56 PM

### CODE REVIEW

**Comment by Noxime** [comment]
I approve this change

**Comment by TheButlah** [comment]
> I approve this change

Did you mean you approve the revert or the screenshotted change?

**Comment by Noxime** [comment]
I agree to the relicensing condition. My code is under both MIT and Apache 2.0 license

**Comment by TheButlah** [comment]
Time to revert the revert XD

**Pull request merged**
